version: '3'
services:
  nginx:
    image: nginx:1.17.2-alpine
    volumes:
      - ./.conf:/etc/nginx
      - ./nginxVolumn:/var/cache/nginx
    links:
      - app
    ports:
      - 3000:80

  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    expose:
      - 3000
